AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  GetBalanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: com.amazon.aws.serverless.airline.Get::handleRequest
      Runtime: java8
      MemorySize: 256
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        GetLoyalty:
          Type: Api
          Properties:
            Path: /loyalty/customerId
            Method: get

  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: com.amazon.aws.serverless.airline.Ingest::handleRequest
      Runtime: java8
      MemorySize: 256
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        GetLoyalty:
          Type: SNS
          Properties:
            Topic: !Ref IngestTopic


  IngestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "IngestTopic"

  LoyaltyLedger:
    Type: AWS::QLDB::Ledger
    Properties:
      DeletionProtection: true
      Name: "loyalty-points"
      PermissionsMode: "ALLOW_ALL"
      Tags:
        - Key: StackId
          Value: !Ref AWS::StackId
        - Key: StackName
          Value: !Ref AWS::StackName


